<a href="https://colab.research.google.com/github/ujwaljain506-hash/ml-journey/blob/main/day14_encoding_features.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
import matplotlib.pyplot as plt

In [1]:
from sklearn.preprocessing import LabelEncoder

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("/content/drive/MyDrive/matches.csv")
print("File Loaded")

File Loaded

In [21]:
le = LabelEncoder()
df['team1_encoded'] = le.fit_transform(df['team1'])

In [22]:
df[['team1','team1_encoded']].head()

                         team1  team1_encoded
0          Sunrisers Hyderabad             14
1               Mumbai Indians              8
2                Gujarat Lions              4
3       Rising Pune Supergiant             11
4  Royal Challengers Bangalore             13

In [26]:
df['team2_encoded'] = le.fit_transform(df['team2'])

In [27]:
df[['team2','team2_encoded']].head()

                         team2  team2_encoded
0  Royal Challengers Bangalore             13
1       Rising Pune Supergiant             11
2        Kolkata Knight Riders              7
3              Kings XI Punjab              5
4             Delhi Daredevils              3

In [29]:
df['venue_encoded']=le.fit_transform(df['venue'])
df['toss_winner_encoded']=le.fit_transform(df['toss_winner'])
df['toss_decision_encoded']=le.fit_transform(df['toss_decision'])

In [30]:
df[['venue', 'venue_encoded', 'toss_winner', 'toss_winner_encoded', 'toss_decision', 'toss_decision_encoded']].head()

,venue,venue_encoded,toss_winner,toss_winner_encoded,toss_decision,toss_decision_encoded
0,"Rajiv Gandhi International Stadium, Uppal",28,Royal Challengers Bangalore,13,field,1
1,Maharashtra Cricket Association Stadium,21,Rising Pune Supergiant,11,field,1
2,Saurashtra Cricket Association Stadium,31,Kolkata Knight Riders,7,field,1
3,Holkar Cricket Stadium,13,Kings XI Punjab,5,field,1
4,M Chinnaswamy Stadium,17,Royal Challengers Bangalore,13,bat,0